export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHACE_BURGER_START = 'PURCHACE_BURGER_START';
export const PURCHACE_BURGER_SUCCESS = 'PURCHACE_BURGER_SUCCESS';
export const PURCHACE_BURGER_FAIL = 'PURCHACE_BURGER_FAIL';
export const PUTCHASE_INIT = 'PUTCHASE_INIT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';